name: 'amos_core'
version: '0.0.1'
config-version: 2

profile: 'default'  # change to your profile name

vars:
  # WORKAROUND for dbt-fusion: Remove recursive var() definitions
  active_source: "example"
  source_package: "amos_source_example"

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  amos_core:
    +materialized: view
    core:
      +schema: public
      +database: core
      # Exclude access_patterns - just documentation, causes dbt-fusion panic
      access_patterns:
        +enabled: false
      reference:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'reference']
      entities:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'entity']
      relationships:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'relationship']
      bridge:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'bridge']
      snapshots:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'snapshot']
      supporting:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'supporting']
      transactions:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'transactions']
    marts:
      +schema: marts
