name: 'amos_core'
version: '0.0.1'
config-version: 2

profile: 'default'  # change to your profile name

vars:
  active_source: "{{ var('active_source', 'example') }}"
  source_package: "{{ var('source_package', 'amos_source_example') }}"

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  amos_core:
    +materialized: view
    staging:
      +schema: stg_core
    core:
      +schema: public
      +database: core
      reference:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'reference']
      entities:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'entity']
      relationships:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'relationship']
      bridge:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'bridge']
      snapshots:
        +materialized: incremental
        +on_schema_change: 'fail'
        +tags: ['bi_accessible', 'canonical', 'snapshot']
      supporting:
        +materialized: table
        +tags: ['bi_accessible', 'canonical', 'supporting']
    marts:
      +schema: marts
