version: 2

models:
  - name: fund
    description: |
      **Investment Fund Master Data**
      
      Core fund information including structure, fees, and performance targets. This is the primary table for fund-level analysis and reporting.
      Join with fund_snapshot for performance metrics and commitment for investor relationships.
      
      **Common BI Use Cases:**
      - Fund performance dashboards and comparisons
      - Vintage year analysis and benchmarking
      - Fee analysis and fund economics
      - Fund structure and jurisdiction reporting
      - LP reporting and investor communications
      
      **Key Relationships:**
      - Join with fund_snapshot on fund.id = fund_snapshot.fund_id for performance metrics
      - Join with commitment on fund.id = commitment.fund_id for investor relationships
      - Join with investment on fund.id = investment.fund_id for portfolio companies
      - Join with currency on fund.base_currency_code = currency.code for currency details
      
      **Refresh Schedule:** Daily at 6:00 AM UTC
      **Data Availability:** Complete fund history from inception
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: varchar(36)
        description: |
          **Primary Key - Fund Identifier**
          
          Unique identifier for each fund. Use this field to join with all fund-related tables.
          
          **BI Usage:** Primary key for all fund-related joins and filters
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: varchar(255)
        description: |
          **Fund Display Name**
          
          Official fund name as it appears in legal documents and investor reports.
          Use for fund selection filters and report headers.
          
          **BI Usage:** Primary display field for fund identification in reports and dashboards
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: type
        data_type: varchar(64)
        description: |
          **Fund Strategy Type**
          
          Investment strategy classification (e.g., 'Growth Equity', 'Buyout', 'Credit', 'Venture Capital').
          Use for strategy-based analysis and peer comparisons.
          
          **BI Usage:** Group funds by strategy for performance benchmarking and analysis
      - name: vintage
        data_type: integer
        description: |
          **Fund Vintage Year**
          
          Year the fund was established or began investing. Critical for vintage-based performance analysis.
          Use for cohort analysis and market cycle comparisons.
          
          **BI Usage:** Primary grouping field for vintage analysis and peer benchmarking
      - name: management_fee
        data_type: decimal(7,4)
        description: |
          **Annual Management Fee Rate**
          
          Annual management fee as a decimal (e.g., 0.0200 = 2.00%).
          Used for fee analysis and fund economics calculations.
          
          **BI Usage:** Calculate total management fees and compare fee structures across funds
          **Typical Range:** 1.5% - 2.5% for most fund types
      - name: hurdle
        data_type: decimal(7,4)
        description: |
          **Preferred Return Hurdle Rate**
          
          Minimum return rate before carried interest is earned, as a decimal (e.g., 0.0800 = 8.00%).
          Critical for carried interest calculations and LP return analysis.
          
          **BI Usage:** Calculate carried interest eligibility and LP preferred returns
          **Typical Range:** 6% - 10% annually
      - name: carried_interest
        data_type: decimal(7,4)
        description: |
          **Carried Interest Rate**
          
          GP's share of profits above the hurdle rate, as a decimal (e.g., 0.2000 = 20.00%).
          Used for GP compensation analysis and net return calculations.
          
          **BI Usage:** Calculate GP carried interest and LP net returns
          **Typical Range:** 15% - 25% of profits above hurdle
      - name: target_commitment
        data_type: numeric(20,2)
        description: |
          **Target Fund Size**
          
          Target total commitment amount in the fund's base currency.
          Compare with actual commitments to track fundraising progress.
          
          **BI Usage:** Calculate fundraising progress and fund size analysis
          **Note:** Amount is in base_currency_code denomination
      - name: incorporated_in
        data_type: varchar(128)
        description: |
          **Jurisdiction of Incorporation**
          
          Legal jurisdiction where the fund is incorporated (e.g., 'Delaware', 'Cayman Islands', 'Luxembourg').
          Important for regulatory reporting and tax analysis.
          
          **BI Usage:** Group funds by jurisdiction for regulatory and tax reporting
      - name: base_currency_code
        data_type: varchar(3)
        description: |
          **Fund Base Currency**
          
          Primary currency for fund accounting and reporting (ISO 3-letter code).
          All fund-level amounts are denominated in this currency unless otherwise specified.
          
          **BI Usage:** Currency conversion and multi-currency fund analysis
          **Join:** currency.code for currency name and details
        tests:
          - relationships:
              to: ref('currency')
              field: code
      - name: created_at
        data_type: text
        description: "System field - Record creation timestamp"
      - name: updated_at
        data_type: text
        description: "System field - Record last update timestamp"
    
  - name: company
    description: |
      **Portfolio Company Master Data**
      
      Master data for portfolio companies linked to equity instruments in the unified instrument model.
      Essential for equity analysis and company-specific reporting through the instrument-centric design.
      
      **Instrument-Centric Integration:**
      - Linked to instruments via instrument.company_id for equity-type instruments
      - Required relationship for EQUITY, CONVERTIBLE, and WARRANT instruments
      - Not used for LOAN or FUND_INTEREST instruments
      
      **Common BI Use Cases:**
      - Company-level equity analysis and performance tracking
      - Industry and geographic analysis through company attributes
      - Portfolio company reporting and due diligence
      - Company valuation and performance metrics
      
      **Key Relationships:**
      - Join with instrument WHERE instrument_type IN ('EQUITY', 'CONVERTIBLE', 'WARRANT')
      - Join with industry for sector analysis
      - Join with company_industry/company_country bridges for allocations
      
      **Query Patterns:**
      ```sql
      -- Equity instruments by company
      SELECT c.name, COUNT(i.id) as instrument_count, SUM(s.fair_value_converted) as total_value
      FROM company c
      JOIN instrument i ON c.id = i.company_id
      JOIN instrument_snapshot s ON i.id = s.instrument_id
      WHERE i.instrument_type = 'EQUITY'
      GROUP BY c.name
      ```
      
      **Refresh Schedule:** Daily at 6:00 AM UTC
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: varchar(36)
        description: "Unique company identifier"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: varchar(255)
        description: "Company name"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: website
        data_type: varchar(255)
        description: "Company website"
      - name: description
        data_type: text
        description: "Company description"
      - name: currency
        data_type: varchar(3)
        description: "Company currency code"
        tests:
          - relationships:
              to: ref('currency')
              field: code
      - name: industry_id
        data_type: varchar(36)
        description: "Foreign key to industry table"
        tests:
          - relationships:
              to: ref('industry')
              field: id
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    
  - name: investor
    description: "Investor entity"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: varchar(36)
        description: "Unique investor identifier"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: varchar(255)
        description: "Investor name"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: investor_type_id
        data_type: varchar(36)
        description: "Foreign key to investor_type table"
        tests:
          - relationships:
              to: ref('investor_type')
              field: id
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    
  - name: counterparty
    description: "Counterparty entity"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: varchar(36)
        description: "Unique counterparty identifier"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: varchar(255)
        description: "Counterparty name"
        constraints:
          - type: not_null
        tests:
          - not_null
          - unique
      - name: type
        data_type: varchar(64)
        description: "Counterparty type"
      - name: country_code
        data_type: char(2)
        description: "Country code"
        tests:
          - relationships:
              to: ref('country')
              field: code
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"