version: 2

models:
  - name: fund
    description: "Investment fund entity"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique fund identifier"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: varchar(255)
        description: "Fund name"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: type
        data_type: varchar(64)
        description: "Fund type"
      - name: vintage
        data_type: integer
        description: "Fund vintage year"
      - name: management_fee
        data_type: decimal(7,4)
        description: "Management fee percentage"
      - name: hurdle
        data_type: decimal(7,4)
        description: "Hurdle rate percentage"
      - name: carried_interest
        data_type: decimal(7,4)
        description: "Carried interest percentage"
      - name: target_commitment
        data_type: numeric(20,2)
        description: "Target commitment amount"
      - name: incorporated_in
        data_type: varchar(128)
        description: "Jurisdiction of incorporation"
      - name: base_currency_code
        data_type: varchar(3)
        description: "Base currency code"
        tests:
          - relationships:
              to: ref('currency')
              field: code
      - name: created_at
        data_type: text
        description: "Record creation timestamp"
      - name: updated_at
        data_type: text
        description: "Record last update timestamp"
    
  - name: company
    description: "Portfolio company entity"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique company identifier"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: varchar(255)
        description: "Company name"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: website
        data_type: varchar(255)
        description: "Company website"
      - name: description
        data_type: text
        description: "Company description"
      - name: currency
        data_type: varchar(3)
        description: "Company currency code"
        tests:
          - relationships:
              to: ref('currency')
              field: code
      - name: industry_id
        data_type: uuid
        description: "Foreign key to industry table"
        tests:
          - relationships:
              to: ref('industry')
              field: id
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    
  - name: investor
    description: "Investor entity"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique investor identifier"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: varchar(255)
        description: "Investor name"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: investor_type_id
        data_type: uuid
        description: "Foreign key to investor_type table"
        tests:
          - relationships:
              to: ref('investor_type')
              field: id
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    
  - name: counterparty
    description: "Counterparty entity"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique counterparty identifier"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        data_type: varchar(255)
        description: "Counterparty name"
        constraints:
          - type: not_null
        tests:
          - not_null
          - unique
      - name: type
        data_type: varchar(64)
        description: "Counterparty type"
      - name: country_code
        data_type: char(2)
        description: "Country code"
        tests:
          - relationships:
              to: ref('country')
              field: code
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"