version: 2

models:
  - name: dim_currency
    description: "Currency dimension table"
    config:
      contract:
        enforced: true
    columns:
      - name: code
        description: "ISO 3-letter currency code"
        data_type: varchar(3)
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        description: "Currency name"
        data_type: varchar(64)
      - name: created_at
        description: "Record creation timestamp"
        data_type: timestamp
      - name: updated_at
        description: "Record last update timestamp"
        data_type: timestamp
    
  - name: dim_country
    description: "Country dimension table"
    config:
      contract:
        enforced: true
    columns:
      - name: code
        description: "ISO 2-letter country code"
        data_type: char(2)
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        description: "Country name"
        data_type: varchar(128)
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: region
        description: "Geographic region"
        data_type: varchar(64)
      - name: subregion
        description: "Geographic subregion"
        data_type: varchar(64)
      - name: created_at
        description: "Record creation timestamp"
        data_type: timestamp
      - name: updated_at
        description: "Record last update timestamp"
        data_type: timestamp
    
  - name: dim_industry
    description: "Industry dimension table"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        description: "Unique industry identifier"
        data_type: uuid
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        description: "Industry name"
        data_type: varchar(128)
        constraints:
          - type: not_null
        tests:
          - not_null
          - unique
      - name: created_at
        description: "Record creation timestamp"
        data_type: timestamp
      - name: updated_at
        description: "Record last update timestamp"
        data_type: timestamp
    
  - name: dim_investor_type
    description: "Investor type dimension table"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        description: "Unique investor type identifier"
        data_type: uuid
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        description: "Investor type name"
        data_type: varchar(128)
      - name: kyc_category
        description: "KYC category"
        data_type: varchar(128)
      - name: created_at
        description: "Record creation timestamp"
        data_type: timestamp
      - name: updated_at
        description: "Record last update timestamp"
        data_type: timestamp
    
  - name: dim_stage
    description: "Investment stage dimension table"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        description: "Unique stage identifier"
        data_type: uuid
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: name
        description: "Stage name"
        data_type: varchar(128)
      - name: type
        description: "Stage type"
        data_type: varchar(64)
      - name: created_at
        description: "Record creation timestamp"
        data_type: timestamp
      - name: updated_at
        description: "Record last update timestamp"
        data_type: timestamp