version: 2

models:
  - name: commitment
    description: "Fund-investor commitment relationships"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique commitment identifier (UUID)"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: fund_id
        data_type: uuid
        description: "Foreign key to fund table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('fund')
              field: id
      - name: investor_id
        data_type: uuid
        description: "Foreign key to investor table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('investor')
              field: id
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    
  - name: investment
    description: "Fund-company investment relationships"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique investment identifier (UUID)"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: fund_id
        data_type: uuid
        description: "Foreign key to fund table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('fund')
              field: id
      - name: company_id
        data_type: uuid
        description: "Foreign key to company table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('company')
              field: id
      - name: description
        data_type: text
        description: "Investment description"
      - name: investment_type
        data_type: varchar(64)
        description: "Type of investment"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    

  - name: opportunity
    description: "Investment opportunity pipeline data"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique opportunity identifier (UUID)"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: fund_id
        data_type: uuid
        description: "Foreign key to fund table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('fund')
              field: id
      - name: name
        data_type: varchar(255)
        description: "Name of the investment opportunity"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: stage_id
        data_type: uuid
        description: "Foreign key to stage table"
        tests:
          - relationships:
              to: ref('stage')
              field: id
      - name: company_id
        data_type: uuid
        description: "Foreign key to company table (optional)"
        tests:
          - relationships:
              to: ref('company')
              field: id
      - name: responsible
        data_type: varchar(255)
        description: "Person responsible for the opportunity"
      - name: amount
        data_type: numeric(20,2)
        description: "Potential investment amount"
      - name: next_step
        data_type: varchar(255)
        description: "Description of next step"
      - name: source
        data_type: varchar(128)
        description: "Source of the opportunity"
      - name: close_date
        data_type: date
        description: "Expected or actual close date"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"