version: 2

models:
  - name: commitment
    description: "Fund-investor commitment relationships"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique commitment identifier (UUID)"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: fund_id
        data_type: uuid
        description: "Foreign key to fund table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('fund')
              field: id
      - name: investor_id
        data_type: uuid
        description: "Foreign key to investor table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('investor')
              field: id
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    
  - name: instrument
    description: |
      **Unified Instrument Model - Core Financial Positions**
      
      Central table for all financial positions including equity investments, loans, convertibles, warrants, and fund interests.
      This unified approach abstracts both private equity and private credit instruments into a single interface while maintaining 
      product-specific attributes through related tables and snapshots.
      
      **Instrument-Centric Design:**
      - All financial positions flow through this unified instrument table
      - Use instrument_type to filter for specific analysis (equity vs loan)
      - Equity-specific data accessed through company relationships and equity fields in snapshots
      - Loan-specific data accessed through basic loan fields (detailed loan data in separate PC package)
      
      **Common BI Use Cases:**
      - Portfolio overview across all instrument types
      - Equity analysis: Filter by instrument_type = 'EQUITY' and join with company data
      - Loan analysis: Filter by instrument_type = 'LOAN' for basic loan reporting
      - Performance tracking: Join with instrument_snapshot for time-series analysis
      - Geographic/industry exposure: Join with instrument_country/instrument_industry bridges
      
      **Key Relationships:**
      - Join with fund on instrument.fund_id = fund.id for fund-level analysis
      - Join with company on instrument.company_id = company.id for equity instruments
      - Join with instrument_snapshot for valuation and performance metrics
      - Join with instrument_cashflow for cashflow analysis
      - Join with instrument_country/instrument_industry for allocation analysis
      
      **Query Patterns:**
      ```sql
      -- Equity portfolio analysis
      SELECT i.*, c.name as company_name, f.name as fund_name
      FROM instrument i
      JOIN company c ON i.company_id = c.id
      JOIN fund f ON i.fund_id = f.id
      WHERE i.instrument_type = 'EQUITY'
      
      -- Loan portfolio analysis  
      SELECT i.*, f.name as fund_name
      FROM instrument i
      JOIN fund f ON i.fund_id = f.id
      WHERE i.instrument_type = 'LOAN'
      ```
      
      **Refresh Schedule:** Daily at 6:00 AM UTC
      **Data Availability:** Complete instrument history from inception
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: varchar(36)
        description: "Unique instrument identifier (UUID)"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: fund_id
        data_type: varchar(36)
        description: "Foreign key to fund table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('fund')
              field: id
      - name: company_id
        data_type: varchar(36)
        description: |
          **Company Reference for Equity Instruments**
          
          Foreign key to company table, required for equity-type instruments (EQUITY, CONVERTIBLE, WARRANT).
          Null for loan instruments and fund interests where no specific company relationship exists.
          
          **Business Rules:**
          - Required (not null) for instrument_type IN ('EQUITY', 'CONVERTIBLE', 'WARRANT')
          - Should be null for instrument_type IN ('LOAN', 'FUND_INTEREST')
          
          **BI Usage:** Join with company table for equity instrument analysis
          **Join Pattern:** JOIN company c ON i.company_id = c.id WHERE i.instrument_type = 'EQUITY'
        constraints:
        tests:
          - relationships:
              to: ref('company')
              field: id
              config:
                where: "company_id IS NOT NULL"
      - name: instrument_type
        data_type: varchar(20)
        description: |
          **Instrument Type Classification**
          
          Defines the type of financial instrument for proper analysis and reporting.
          Critical field for filtering and grouping instruments by product type.
          
          **Valid Values:**
          - EQUITY: Direct equity investments in portfolio companies
          - LOAN: Loan instruments and credit facilities  
          - CONVERTIBLE: Convertible securities (debt/equity hybrid)
          - WARRANT: Warrant instruments for future equity acquisition
          - FUND_INTEREST: Interests in other funds (fund-of-funds)
          
          **BI Usage:** Primary filter for product-specific analysis and reporting
          **Query Pattern:** WHERE instrument_type = 'EQUITY' for equity-only analysis
        constraints:
          - type: not_null
        tests:
          - not_null
          - accepted_values:
              values: ['EQUITY', 'LOAN', 'CONVERTIBLE', 'WARRANT', 'FUND_INTEREST']
              quote: true
      - name: base_currency_code
        data_type: varchar(3)
        description: "Base currency code for the instrument"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('currency')
              field: code
      - name: inception_date
        data_type: date
        description: "Date when the instrument was created/acquired"
      - name: termination_date
        data_type: date
        description: "Date when the instrument was terminated/disposed"
      - name: description
        data_type: text
        description: "Instrument description"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    

  - name: opportunity
    description: "Investment opportunity pipeline data"
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique opportunity identifier (UUID)"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: fund_id
        data_type: uuid
        description: "Foreign key to fund table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('fund')
              field: id
      - name: name
        data_type: varchar(255)
        description: "Name of the investment opportunity"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: stage_id
        data_type: uuid
        description: "Foreign key to stage table"
        tests:
          - relationships:
              to: ref('stage')
              field: id
      - name: company_id
        data_type: uuid
        description: "Foreign key to company table (optional)"
        tests:
          - relationships:
              to: ref('company')
              field: id
      - name: responsible
        data_type: varchar(255)
        description: "Person responsible for the opportunity"
      - name: amount
        data_type: numeric(20,2)
        description: "Potential investment amount"
      - name: next_step
        data_type: varchar(255)
        description: "Description of next step"
      - name: source
        data_type: varchar(128)
        description: "Source of the opportunity"
      - name: close_date
        data_type: date
        description: "Expected or actual close date"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"