version: 2

models:
  - name: fund_snapshot
    description: "Point-in-time fund performance metrics with incremental loading. Updated daily with fund NAV, commitment, and performance calculations."
    config:
      contract:
        enforced: true
    columns:
      - name: fund_id
        data_type: uuid
        description: "Foreign key to fund table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('fund')
              field: id
      - name: as_of_date
        data_type: date
        description: "Snapshot date for the performance metrics"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: total_nav
        data_type: numeric(20,2)
        description: "Total Net Asset Value as of the snapshot date"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: total_commitment
        data_type: numeric(20,2)
        description: "Total commitment amount for the fund"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: total_called
        data_type: numeric(20,2)
        description: "Total amount called from investors"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: total_distributed
        data_type: numeric(20,2)
        description: "Total amount distributed to investors"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: dpi
        data_type: decimal(10,4)
        description: "Distributions to Paid-In capital ratio"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: rvpi
        data_type: decimal(10,4)
        description: "Residual Value to Paid-In capital ratio"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: expected_coc
        data_type: decimal(10,4)
        description: "Expected Cash-on-Cash return multiple"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
        constraints:
          - type: not_null
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
        constraints:
          - type: not_null
    tests:
      - unique:
          column_name: "fund_id || '|' || as_of_date"
      - dbt_utils.expression_is_true:
          expression: "total_called <= total_commitment OR total_commitment IS NULL OR total_called IS NULL"
          config:
            severity: error
      - dbt_utils.expression_is_true:
          expression: "as_of_date <= CURRENT_DATE()"
          config:
            severity: error
    
  - name: commitment_snapshot
    description: "Point-in-time commitment snapshots"
    
  - name: instrument_snapshot
    description: "Unified point-in-time snapshots for all instrument types (equity and loan) with comprehensive valuation and performance tracking. Updated daily with instrument-specific metrics."
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: varchar(36)
        description: "Unique snapshot record identifier (UUID)"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: instrument_id
        data_type: varchar(36)
        description: "Foreign key to instrument table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('instrument')
              field: id
      - name: as_of_date
        data_type: date
        description: "Snapshot date for the instrument valuation"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: currency_code
        data_type: varchar(3)
        description: "Currency code for the snapshot values"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('currency')
              field: code
      - name: fx_rate
        data_type: decimal(10,6)
        description: "Foreign exchange rate to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      - name: fair_value
        data_type: numeric(20,2)
        description: "Fair value of the instrument in original currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: amortized_cost
        data_type: numeric(20,2)
        description: "Amortized cost of the instrument in original currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: fair_value_converted
        data_type: numeric(20,2)
        description: "Fair value converted to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: amortized_cost_converted
        data_type: numeric(20,2)
        description: "Amortized cost converted to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: principal_outstanding
        data_type: numeric(20,2)
        description: "Outstanding principal amount (loan instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: undrawn_commitment
        data_type: numeric(20,2)
        description: "Undrawn commitment amount (loan instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: accrued_income
        data_type: numeric(20,2)
        description: "Accrued income amount (loan instruments only)"
      - name: accrued_fees
        data_type: numeric(20,2)
        description: "Accrued fees amount (loan instruments only)"
      - name: principal_outstanding_converted
        data_type: numeric(20,2)
        description: "Outstanding principal converted to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: undrawn_commitment_converted
        data_type: numeric(20,2)
        description: "Undrawn commitment converted to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: accrued_income_converted
        data_type: numeric(20,2)
        description: "Accrued income converted to base currency"
      - name: accrued_fees_converted
        data_type: numeric(20,2)
        description: "Accrued fees converted to base currency"
      - name: equity_stake_pct
        data_type: decimal(5,2)
        description: "Equity ownership percentage (equity instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true
      - name: equity_dividends_cum
        data_type: numeric(20,2)
        description: "Cumulative dividends received (equity instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: equity_exit_proceeds_actual
        data_type: numeric(20,2)
        description: "Actual exit proceeds (equity instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: equity_exit_proceeds_forecast
        data_type: numeric(20,2)
        description: "Forecasted exit proceeds (equity instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: source
        data_type: varchar(20)
        description: "Source of the snapshot data"
        constraints:
          - type: not_null
        tests:
          - not_null
          - accepted_values:
              values: ['ADMIN', 'INTERNAL']
              quote: true
      - name: source_file_ref
        data_type: varchar(255)
        description: "Reference to source file or system"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
        constraints:
          - type: not_null
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
        constraints:
          - type: not_null
    tests:
      - unique:
          column_name: "instrument_id || '|' || as_of_date || '|' || source"
      - dbt_utils.expression_is_true:
          expression: "as_of_date <= CURRENT_DATE()"
          config:
            severity: error
    

  - name: company_performance_snapshot
    description: "Point-in-time company performance metrics"
    
  - name: transaction
    description: "All financial transactions across the platform with comprehensive transaction tracking. Includes capital calls, distributions, investments, loan activities, and operational transactions."
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: uuid
        description: "Unique transaction identifier"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: fund_id
        data_type: uuid
        description: "Foreign key to fund table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('fund')
              field: id
      - name: investment_id
        data_type: uuid
        description: "Foreign key to investment table (for investment-related transactions)"
        tests:
          - relationships:
              to: ref('investment')
              field: id

      - name: commitment_id
        data_type: uuid
        description: "Foreign key to commitment table (for capital call/distribution transactions)"
        tests:
          - relationships:
              to: ref('commitment')
              field: id
      - name: tx_type
        data_type: varchar(20)
        description: "Transaction type classification"
        constraints:
          - type: not_null
        tests:
          - not_null
          - accepted_values:
              values: ['CAPITAL_CALL', 'DISTRIBUTION', 'INVESTMENT', 'DIVESTMENT', 'LOAN_DRAW', 'LOAN_REPAYMENT', 'INTEREST_PAYMENT', 'FEE_PAYMENT', 'EXPENSE', 'INCOME', 'TRANSFER']
      - name: transaction_date
        data_type: date
        description: "Date when the transaction occurred"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: amount
        data_type: numeric(20,2)
        description: "Transaction amount (positive for inflows, negative for outflows)"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: currency_code
        data_type: varchar(3)
        description: "Currency code for the transaction amount"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('currency')
              field: code
      - name: description
        data_type: text
        description: "Transaction description or memo"
      - name: reference_number
        data_type: varchar(100)
        description: "External reference number or identifier"
      - name: counterparty_id
        data_type: uuid
        description: "Foreign key to counterparty table (for external transactions)"
        tests:
          - relationships:
              to: ref('counterparty')
              field: id
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
        constraints:
          - type: not_null
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
        constraints:
          - type: not_null
    tests:
      - dbt_utils.expression_is_true:
          expression: "transaction_date <= CURRENT_DATE()"
          config:
            severity: error
    
