version: 2

models:
  - name: fund_snapshot
    description: "Point-in-time fund performance metrics with incremental loading. Updated daily with fund NAV, commitment, and performance calculations."
    config:
      contract:
        enforced: true
    columns:
      - name: fund_id
        data_type: uuid
        description: "Foreign key to fund table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('fund')
              field: id
      - name: as_of_date
        data_type: date
        description: "Snapshot date for the performance metrics"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: total_nav
        data_type: numeric(20,2)
        description: "Total Net Asset Value as of the snapshot date"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: total_commitment
        data_type: numeric(20,2)
        description: "Total commitment amount for the fund"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: total_called
        data_type: numeric(20,2)
        description: "Total amount called from investors"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: total_distributed
        data_type: numeric(20,2)
        description: "Total amount distributed to investors"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: dpi
        data_type: decimal(10,4)
        description: "Distributions to Paid-In capital ratio"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: rvpi
        data_type: decimal(10,4)
        description: "Residual Value to Paid-In capital ratio"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: expected_coc
        data_type: decimal(10,4)
        description: "Expected Cash-on-Cash return multiple"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
        constraints:
          - type: not_null
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
        constraints:
          - type: not_null
    tests:
      - unique:
          column_name: "fund_id || '|' || as_of_date"
      - dbt_utils.expression_is_true:
          expression: "total_called <= total_commitment OR total_commitment IS NULL OR total_called IS NULL"
          config:
            severity: error
      - dbt_utils.expression_is_true:
          expression: "as_of_date <= CURRENT_DATE()"
          config:
            severity: error
    
  
    
  - name: instrument_snapshot
    description: |
      **Unified Instrument Snapshots - Point-in-Time Valuations**
      
      Comprehensive point-in-time snapshots for all instrument types with unified valuation and performance tracking.
      Handles both equity and loan instruments through a single interface with instrument-specific fields.
      
      **Instrument-Centric Design:**
      - Single table for all instrument type snapshots (equity, loan, convertible, etc.)
      - Common valuation fields (fair_value, amortized_cost) for all instruments
      - Equity-specific fields (equity_stake_pct, dividends, exit proceeds) for equity instruments
      - Basic loan fields (principal_outstanding, accrued_income) for loan instruments
      - Currency conversion support for multi-currency portfolios
      
      **Field Population by Instrument Type:**
      - **EQUITY instruments:** fair_value, equity_stake_pct, equity_dividends_cum, equity_exit_proceeds_*
      - **LOAN instruments:** fair_value, amortized_cost, principal_outstanding, accrued_income, accrued_fees
      - **All instruments:** fair_value, currency fields, source tracking
      
      **Common BI Use Cases:**
      - Portfolio valuation across all instrument types
      - Performance tracking over time by instrument type
      - Currency exposure analysis and conversion
      - Equity-specific analysis (stake percentages, dividends, exits)
      - Basic loan analysis (outstanding balances, accrued amounts)
      
      **Key Relationships:**
      - Join with instrument to get instrument type and details
      - Join with currency for currency conversion and display
      - Time-series analysis using as_of_date for trend analysis
      
      **Query Patterns:**
      ```sql
      -- Latest portfolio valuation by instrument type
      SELECT i.instrument_type, SUM(s.fair_value_converted) as total_value
      FROM instrument_snapshot s
      JOIN instrument i ON s.instrument_id = i.id
      WHERE s.as_of_date = (SELECT MAX(as_of_date) FROM instrument_snapshot)
      GROUP BY i.instrument_type
      
      -- Equity performance tracking
      SELECT s.as_of_date, s.equity_stake_pct, s.fair_value_converted
      FROM instrument_snapshot s
      JOIN instrument i ON s.instrument_id = i.id
      WHERE i.instrument_type = 'EQUITY' AND i.id = 'specific_instrument_id'
      ORDER BY s.as_of_date
      ```
      
      **Refresh Schedule:** Daily at 7:00 AM UTC (after instrument updates)
      **Data Availability:** Complete snapshot history with daily granularity
    config:
      contract:
        enforced: true
    columns:
      - name: id
        data_type: varchar(36)
        description: "Unique snapshot record identifier (UUID)"
        constraints:
          - type: not_null
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: instrument_id
        data_type: varchar(36)
        description: "Foreign key to instrument table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('instrument')
              field: id
      - name: as_of_date
        data_type: date
        description: "Snapshot date for the instrument valuation"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: currency_code
        data_type: varchar(3)
        description: "Currency code for the snapshot values"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('currency')
              field: code
      - name: fx_rate
        data_type: decimal(10,6)
        description: "Foreign exchange rate to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false
      - name: fair_value
        data_type: numeric(20,2)
        description: "Fair value of the instrument in original currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: amortized_cost
        data_type: numeric(20,2)
        description: "Amortized cost of the instrument in original currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: fair_value_converted
        data_type: numeric(20,2)
        description: "Fair value converted to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: amortized_cost_converted
        data_type: numeric(20,2)
        description: "Amortized cost converted to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: principal_outstanding
        data_type: numeric(20,2)
        description: "Outstanding principal amount (loan instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: undrawn_commitment
        data_type: numeric(20,2)
        description: "Undrawn commitment amount (loan instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: accrued_income
        data_type: numeric(20,2)
        description: "Accrued income amount (loan instruments only)"
      - name: accrued_fees
        data_type: numeric(20,2)
        description: "Accrued fees amount (loan instruments only)"
      - name: principal_outstanding_converted
        data_type: numeric(20,2)
        description: "Outstanding principal converted to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: undrawn_commitment_converted
        data_type: numeric(20,2)
        description: "Undrawn commitment converted to base currency"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: accrued_income_converted
        data_type: numeric(20,2)
        description: "Accrued income converted to base currency"
      - name: accrued_fees_converted
        data_type: numeric(20,2)
        description: "Accrued fees converted to base currency"
      - name: equity_stake_pct
        data_type: decimal(5,2)
        description: "Equity ownership percentage (equity instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              inclusive: true
      - name: equity_dividends_cum
        data_type: numeric(20,2)
        description: "Cumulative dividends received (equity instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: equity_exit_proceeds_actual
        data_type: numeric(20,2)
        description: "Actual exit proceeds (equity instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: equity_exit_proceeds_forecast
        data_type: numeric(20,2)
        description: "Forecasted exit proceeds (equity instruments only)"
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: true
      - name: source
        data_type: varchar(20)
        description: "Source of the snapshot data"
        constraints:
          - type: not_null
        tests:
          - not_null
          - accepted_values:
              values: ['ADMIN', 'INTERNAL']
              quote: true
      - name: source_file_ref
        data_type: varchar(255)
        description: "Reference to source file or system"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
        constraints:
          - type: not_null
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
        constraints:
          - type: not_null
    tests:
      - unique:
          column_name: "instrument_id || '|' || as_of_date || '|' || source"
      - dbt_utils.expression_is_true:
          expression: "as_of_date <= CURRENT_DATE()"
          config:
            severity: error
    

  
    

    
