version: 2

models:
  - name: fund_snapshot
    description: "Point-in-time fund performance metrics with incremental loading"
    
  - name: commitment_snapshot
    description: "Point-in-time commitment snapshots"
    
  - name: investment_snapshot
    description: "Point-in-time investment valuations"
    
  - name: loan_snapshot
    description: "Point-in-time loan positions and valuations"
    
  - name: company_performance_snapshot
    description: "Point-in-time company performance metrics"
    
  - name: transaction
    description: "All financial transactions across the platform"
    
  - name: loan_cashflow
    description: "Detailed loan payment and draw tracking"