version: 2

models:
  - name: company_industry
    description: "Many-to-many relationship between companies and industries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: company_id
        data_type: uuid
        description: "Foreign key to company table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('company')
              field: id
      - name: industry_id
        data_type: uuid
        description: "Foreign key to industry table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('industry')
              field: id
      - name: primary_flag
        data_type: boolean
        description: "Flag indicating if this is the primary industry for the company"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this industry (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - company_id
            - industry_id
    
  - name: company_country
    description: "Many-to-many relationship between companies and countries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: company_id
        data_type: uuid
        description: "Foreign key to company table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('company')
              field: id
      - name: country_code
        data_type: char(2)
        description: "Foreign key to country table (ISO 2-letter code)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('country')
              field: code
      - name: primary_flag
        data_type: boolean
        description: "Flag indicating if this is the primary country for the company"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this country (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - company_id
            - country_code
    

  - name: opportunity_country
    description: "Many-to-many relationship between opportunities and countries"
    
  - name: opportunity_industry
    description: "Many-to-many relationship between opportunities and industries"