version: 2

models:
  - name: company_industry
    description: "Many-to-many relationship between companies and industries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: company_id
        data_type: uuid
        description: "Foreign key to company table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('company')
              field: id
      - name: industry_id
        data_type: uuid
        description: "Foreign key to industry table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('industry')
              field: id
      - name: primary_flag
        data_type: boolean
        description: "Flag indicating if this is the primary industry for the company"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this industry (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - company_id
            - industry_id
    
  - name: company_country
    description: "Many-to-many relationship between companies and countries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: company_id
        data_type: uuid
        description: "Foreign key to company table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('company')
              field: id
      - name: country_code
        data_type: char(2)
        description: "Foreign key to country table (ISO 2-letter code)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('country')
              field: code
      - name: primary_flag
        data_type: boolean
        description: "Flag indicating if this is the primary country for the company"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this country (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - company_id
            - country_code
    
  - name: facility_country
    description: "Time-variant many-to-many relationship between facilities and countries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: facility_id
        data_type: uuid
        description: "Foreign key to facility table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('facility')
              field: id
      - name: country_code
        data_type: char(2)
        description: "Foreign key to country table (ISO 2-letter code)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('country')
              field: code
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this country (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: valid_from
        data_type: date
        description: "Start date for this allocation"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: valid_to
        data_type: date
        description: "End date for this allocation (NULL if current)"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - facility_id
            - country_code
            - valid_from
    
  - name: facility_industry
    description: "Time-variant many-to-many relationship between facilities and industries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: facility_id
        data_type: uuid
        description: "Foreign key to facility table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('facility')
              field: id
      - name: industry_id
        data_type: uuid
        description: "Foreign key to industry table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('industry')
              field: id
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this industry (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: valid_from
        data_type: date
        description: "Start date for this allocation"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: valid_to
        data_type: date
        description: "End date for this allocation (NULL if current)"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - facility_id
            - industry_id
            - valid_from
    
  - name: facility_lender
    description: "Many-to-many relationship between facilities and lenders with syndicate roles and allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: facility_id
        data_type: uuid
        description: "Foreign key to facility table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('facility')
              field: id
      - name: lender_counterparty_id
        data_type: uuid
        description: "Foreign key to counterparty table (lender)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('counterparty')
              field: id
      - name: syndicate_role
        data_type: varchar(50)
        description: "Role of the lender in the syndicate"
        constraints:
          - type: not_null
        tests:
          - not_null
          - accepted_values:
              values: ['AGENT', 'LEAD_ARRANGER', 'BOOKRUNNER', 'PARTICIPANT', 'CLUB_MEMBER']
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this lender (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: commitment_amount
        data_type: numeric(24,2)
        description: "Commitment amount from this lender"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - facility_id
            - lender_counterparty_id
    
  - name: loan_country
    description: "Time-variant many-to-many relationship between loans and countries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: loan_id
        data_type: uuid
        description: "Foreign key to loan table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('loan')
              field: id
      - name: country_code
        data_type: char(2)
        description: "Foreign key to country table (ISO 2-letter code)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('country')
              field: code
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this country (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: valid_from
        data_type: date
        description: "Start date for this allocation"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: valid_to
        data_type: date
        description: "End date for this allocation (NULL if current)"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - loan_id
            - country_code
            - valid_from
    
  - name: loan_industry
    description: "Time-variant many-to-many relationship between loans and industries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: loan_id
        data_type: uuid
        description: "Foreign key to loan table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('loan')
              field: id
      - name: industry_id
        data_type: uuid
        description: "Foreign key to industry table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('industry')
              field: id
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this industry (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: valid_from
        data_type: date
        description: "Start date for this allocation"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: valid_to
        data_type: date
        description: "End date for this allocation (NULL if current)"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - loan_id
            - industry_id
            - valid_from
    
  - name: opportunity_country
    description: "Many-to-many relationship between opportunities and countries"
    
  - name: opportunity_industry
    description: "Many-to-many relationship between opportunities and industries"