version: 2

models:
  - name: company_industry
    description: "Many-to-many relationship between companies and industries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: company_id
        data_type: uuid
        description: "Foreign key to company table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('company')
              field: id
      - name: industry_id
        data_type: uuid
        description: "Foreign key to industry table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('industry')
              field: id
      - name: primary_flag
        data_type: boolean
        description: "Flag indicating if this is the primary industry for the company"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this industry (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - company_id
            - industry_id
    
  - name: company_country
    description: "Many-to-many relationship between companies and countries with allocation percentages"
    config:
      contract:
        enforced: true
    columns:
      - name: company_id
        data_type: uuid
        description: "Foreign key to company table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('company')
              field: id
      - name: country_code
        data_type: char(2)
        description: "Foreign key to country table (ISO 2-letter code)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('country')
              field: code
      - name: primary_flag
        data_type: boolean
        description: "Flag indicating if this is the primary country for the company"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this country (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - company_id
            - country_code
    

  - name: instrument_country
    description: |
      **Instrument Geographic Allocation Bridge**
      
      Temporal many-to-many relationship between instruments and countries with allocation percentages.
      Supports both equity and loan instruments with time-based allocation tracking for regulatory and risk reporting.
      
      **Instrument-Centric Design:**
      - Works with all instrument types (equity, loan, convertible, etc.)
      - Temporal validity allows allocation changes over time
      - Supports multiple country allocations per instrument
      - Role field distinguishes different country relationships
      
      **Common BI Use Cases:**
      - Geographic exposure analysis across all instrument types
      - Country-based risk reporting and concentration analysis
      - Regulatory reporting by jurisdiction
      - Time-series geographic allocation tracking
      
      **Key Relationships:**
      - Join with instrument to get instrument details and type
      - Join with country for country names and regional groupings
      - Filter by valid_from/valid_to for point-in-time analysis
      
      **Query Patterns:**
      ```sql
      -- Current geographic exposure by instrument type
      SELECT i.instrument_type, c.name as country, ic.allocation_pct
      FROM instrument_country ic
      JOIN instrument i ON ic.instrument_id = i.id  
      JOIN country c ON ic.country_code = c.code
      WHERE ic.valid_to IS NULL  -- Current allocations
      
      -- Primary country for each instrument
      SELECT instrument_id, country_code, allocation_pct
      FROM instrument_country
      WHERE primary_flag = true AND valid_to IS NULL
      ```
      
      **Refresh Schedule:** Daily with instrument updates
    config:
      contract:
        enforced: true
    columns:
      - name: instrument_id
        data_type: varchar(36)
        description: "Foreign key to instrument table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('instrument')
              field: id
      - name: country_code
        data_type: char(2)
        description: "Foreign key to country table (ISO 2-letter code)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('country')
              field: code
      - name: valid_from
        data_type: date
        description: "Start date for this allocation"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: valid_to
        data_type: date
        description: "End date for this allocation (null for current)"
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this country (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: role
        data_type: varchar(50)
        description: "Role of the country (e.g., 'DOMICILE', 'OPERATIONS', 'INVESTMENT')"
        tests:
          - accepted_values:
              values: ['DOMICILE', 'OPERATIONS', 'INVESTMENT', 'REGULATORY']
              quote: true
      - name: primary_flag
        data_type: boolean
        description: "Flag indicating if this is the primary country for the instrument"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - instrument_id
            - country_code
            - valid_from

  - name: instrument_industry
    description: |
      **Instrument Industry Allocation Bridge**
      
      Temporal many-to-many relationship between instruments and industries with allocation percentages.
      Supports sector analysis across all instrument types with time-based allocation tracking.
      
      **Instrument-Centric Design:**
      - Works with all instrument types (equity, loan, convertible, etc.)
      - Temporal validity allows industry allocation changes over time
      - Supports multiple industry allocations per instrument
      - Primary flag identifies main industry classification
      
      **Common BI Use Cases:**
      - Sector exposure analysis across portfolio
      - Industry concentration risk reporting
      - Sector performance analysis by instrument type
      - Time-series industry allocation tracking
      
      **Key Relationships:**
      - Join with instrument to get instrument details and type
      - Join with industry for industry names and classifications
      - Filter by valid_from/valid_to for point-in-time analysis
      
      **Query Patterns:**
      ```sql
      -- Current industry exposure by instrument type
      SELECT i.instrument_type, ind.name as industry, ii.allocation_pct
      FROM instrument_industry ii
      JOIN instrument i ON ii.instrument_id = i.id
      JOIN industry ind ON ii.industry_id = ind.id
      WHERE ii.valid_to IS NULL  -- Current allocations
      
      -- Primary industry for each instrument
      SELECT instrument_id, industry_id, allocation_pct
      FROM instrument_industry
      WHERE primary_flag = true AND valid_to IS NULL
      ```
      
      **Refresh Schedule:** Daily with instrument updates
    config:
      contract:
        enforced: true
    columns:
      - name: instrument_id
        data_type: varchar(36)
        description: "Foreign key to instrument table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('instrument')
              field: id
      - name: industry_id
        data_type: uuid
        description: "Foreign key to industry table"
        constraints:
          - type: not_null
        tests:
          - not_null
          - relationships:
              to: ref('industry')
              field: id
      - name: allocation_pct
        data_type: decimal(5,2)
        description: "Percentage allocation to this industry (0-100)"
        constraints:
          - type: not_null
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
      - name: primary_flag
        data_type: boolean
        description: "Flag indicating if this is the primary industry for the instrument"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: valid_from
        data_type: date
        description: "Start date for this allocation"
        constraints:
          - type: not_null
        tests:
          - not_null
      - name: valid_to
        data_type: date
        description: "End date for this allocation (null for current)"
      - name: created_at
        data_type: timestamp
        description: "Record creation timestamp"
      - name: updated_at
        data_type: timestamp
        description: "Record last update timestamp"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - instrument_id
            - industry_id
            - valid_from

  
  